spring.datasource.url=jdbc:mysql://localhost:3306/db_security?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.thymeleaf.cache=false
